---

api_url_prefix: "req"
static_url_prefix: "app"
server_instance_prefix: sample
basic_auth_realm: flashflood_server_sample

sqlite_base_dir: "resources"
specs_base_dir: "resources"
report_template_dir: "report_tmpl"
web_build_dir: "node_modules/kiwiii/docs/_build"

compound_id_placeholder: |
  DB00186
  DB00189
  DB00193
  DB00203
  DB00764
  DB00863
  DB00865
  DB00868
  DB01143
  DB01240
  DB01242
  DB01361
  DB01366
  DB02638
  DB02959

user:
  guest:
    password: pass
  admin:
    password: admin
