---

api_url_prefix: req
app_bundle_url_prefix: app
assets_url_prefix: assets
server_instance_prefix: sample
basic_auth_realm: flashflood_server_sample

sqlite_base_dir: "resources"
specs_base_dir: "resources"
temporary_file_dir: "tmp"
report_template_dir: "report_tmpl"
web_build_dir: "node_modules/kiwiii/docs/app"
web_debug_build_dir: "node_modules/kiwiii/docs/_build"
web_assets_dir: "node_modules/kiwiii/docs/assets"

externals:
  - name: "KEGG"
    module: "contrib.kegg"

user:
  guest:
    password: pass
  admin:
    password: admin
