---
basic_auth_realm: data server
user:
  guest:
    password: pass
  admin:
    password: admin
sqlite_base_dir: "resources"
api_base_dir: "resources"
report_template_dir: "report_tmpl"
web_build: "node_modules/kiwiii-client/_build"
web_dist: "node_modules/kiwiii-client/dist"
